# Generated by Django 4.1 on 2022-08-11 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='listings',
            field=models.ManyToManyField(blank=True, related_name='categories', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='Default', max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='listings.profile'),
        ),
    ]
